web_server

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,9 +1,24 @@
 #!/usr/bin/env bash
-# Bash script that transfers a file from our client to a server
-
-if [$# -lt 4]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if 4 arguments are passed
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-scp -o "stricthostkeychecking no" -i "$4" "$1" "$3@$2:~/"
+# Assign variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# Transfer the file using SCP
+scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
+
+# Capture SCP exit status
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
+    exit 0  # Success
+else
+    echo "File transfer failed."
+    exit 1  # Failure
+fi
